### ISSUE TITLE
About the license for this model

### ISSUE THREAD

**Issue by PINTO0309** [dwHou/EMDC-PyTorch#2]
Thank you for sharing your great code. :smiley_cat:

What is the license for this model? I'd like to cite it to the repository I'm working on if possible, but I want to post the license correctly.
https://github.com/PINTO0309/PINTO_model_zoo

Thank you.

**Comment by dwHou** [comment]
You're welcome : )  I've added an MIT License.
For these types of localconv [[1](https://openaccess.thecvf.com/content_cvpr_2014/papers/Taigman_DeepFace_Closing_the_2014_CVPR_paper.pdf)], i.e. convolutions without weight sharing, graph optimization is well worth exploring.

**Comment by PINTO0309** [comment]
i see. Thanks!
