### ISSUE TITLE
想问下这个深度填充对人像的深度补充有泛化性吗

### ISSUE THREAD

**Issue by fuzhaiping** [dwHou/EMDC-PyTorch#6]
您好，论文中所展示的深度填充大多为场景，想问下该模型对人物深度填充有泛化性吗？还是需要自己重新训练？

**Comment by dwHou** [comment]
你好👋 这里有几张人像的[结果](https://github.com/dwHou/EMDC-PyTorch/blob/main/Submit/results/00002_depth_sparse_jet.png)，可以看到有一定的泛化能力，我认为深度补全模型更受所输入的稀疏深度的质量的影响。
