### ISSUE TITLE
have you done experiments on the NYU or KITTI depth completion datasets?

### ISSUE THREAD

**Issue by yudmoe** [dwHou/EMDC-PyTorch#8]
I am very interested in the FCSPN structure you proposed, and want to compare this method with several mainstream depth completion methods. So please tell me if you have done experiments on the NYU or KITTI dataset

我对您提出的FCSPN结构非常感兴趣，想对比一下这个方法和几个主流深度补全方法。所以请教一下您是否在NYU或者KITTI数据集上做过实验

**Comment by dwHou** [comment]
我们由于workshop提供写作论文的时间非常有限，没有能在NYU或者KITTI数据集上做实验，欢迎尝试！
